# Generated by Django 3.1.6 on 2021-03-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frolferapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frolferapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frolferapi.course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frolferapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frolferapi.hole')),
                ('score_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frolferapi.scorecard')),
            ],
        ),
    ]
